[package]
name = "c_hash_sig_crust"
version = "0.2.0"
edition = "2021"

[lib]
name = "c_hash_sig_crust"
crate-type = ["cdylib", "staticlib"]

[dependencies]
hashsig = { git = "https://github.com/b-wagn/hash-sig" }
rand = "0.9"
bincode = { version = "2.0.1", features = ["serde"] }
serde_json = "1.0"

[build-dependencies]
build-helper = { path = "../build-helper" }
