[package]
name = "c_hash_sig_crust"
version = "0.2.0"
edition = "2021"

[lib]
name = "c_hash_sig_crust"
crate-type = ["cdylib", "staticlib"]

[dependencies]
cpp = { path = "../cpp" }
lean-multisig = { git = "https://github.com/qdrvm/leanMultisig.git", rev = "f8af43ada841473072b36e5e51b606ec33f608e8" }
leansig = { git = "https://github.com/leanEthereum/leanSig" }
rand = "0.9.2"
serde_json = "1.0"

[build-dependencies]
build-helper = { path = "../build-helper" }
