name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive        

      - name: Cache folders
        uses: actions/cache@v4
        with:
          path: |
            build
            build-debug
          key: ${{ runner.os }}-build-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build test
        working-directory: .ci
        run: bash build_test.sh
        
      - name: Check generated files
        working-directory: .ci
        run: python3 check_files.py
        
      - name: Run cargo tests
        working-directory: .ci
        run: bash cargo_tests.sh

#      - name: Run tests
#        working-directory: .ci
#        run: bash run_all_tests.sh
        
